"""Astrometric star catalogue with proper motion.

The renderer previously drew its stars from
``simulator.environmental_optics.procedural_star_catalogue``: 3,500 positions
and magnitudes generated by ``np.random``. That field is deterministic, which
made it stable between runs, but it is not the sky — it is confidence grade D
sitting in a module otherwise full of grade C physics.

This module reads a real catalogue, propagates each star from its J2000
reference epoch by its proper motion, and transforms the whole set into
apparent horizontal coordinates with one matrix multiply per frame rather than
one library call per star.

The transform chain is the library's own: :func:`astronomy.Rotation_EQJ_HOR`
supplies precession, nutation, and diurnal rotation together. Annual aberration
is not carried by that rotation, so it is applied separately from the Earth's
barycentric velocity; without it the catalogue disagrees with the library's
per-star path by up to 18 arcseconds.

No catalogue ships with the repository. ``tools/import_star_catalogue.py``
fetches one and records its provenance; until it is run, the renderer falls back
to the procedural field and says so.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
import math
from pathlib import Path

import astronomy
import numpy as np

from .color import blackbody_rgb, color_temperature_from_bv
from .provenance import ConfidenceGrade

J2000_EPOCH = datetime(2000, 1, 1, 12, 0, 0, tzinfo=timezone.utc)
"""The J2000.0 reference epoch, 2000 January 1.5 TT (approximated as UTC)."""

JULIAN_YEAR_DAYS = 365.25

SPEED_OF_LIGHT_AU_PER_DAY = 173.144_632_674_240
"""Astronomical unit per day, the units Astronomy Engine reports velocity in."""


def annual_aberration_velocity(time: astronomy.Time) -> np.ndarray:
    """Earth's barycentric velocity as a fraction of the speed of light.

    Returned in J2000 equatorial coordinates, the same frame the catalogue's
    unit vectors live in. Its magnitude is about 1e-4, which is the classical
    aberration constant of 20.5 arcseconds.
    """

    state = astronomy.BaryState(astronomy.Body.Earth, time)
    return (
        np.array([state.vx, state.vy, state.vz], dtype=np.float64)
        / SPEED_OF_LIGHT_AU_PER_DAY
    )

DEFAULT_CATALOGUE_PATH = (
    Path(__file__).resolve().parent.parent / "assets" / "star_catalogue.npz"
)


def _rotation_matrix(rotation: astronomy.RotationMatrix) -> np.ndarray:
    """Return a NumPy matrix that transforms column vectors.

    Astronomy Engine stores ``rot[i][j]`` as the contribution of source
    component ``i`` to target component ``j``, so the array read directly is the
    transpose of the matrix NumPy needs on the left of a column vector. This is
    verified against the library's own horizon routine by validation metric
    V-20.
    """

    return np.asarray(rotation.rot, dtype=np.float64).T


def eus_to_equatorial_matrix(
    time: astronomy.Time, observer: astronomy.Observer
) -> np.ndarray:
    """Matrix taking a local East-Up-South ray to J2000 equatorial coordinates.

    The renderer's sky shader works in East-Up-South. Passing this matrix as a
    uniform lets the catalogue live in a fixed celestial frame instead of being
    re-rasterised as the sky rotates.
    """

    horizontal_to_equatorial = _rotation_matrix(
        astronomy.Rotation_HOR_EQJ(time, observer)
    )
    # Astronomy Engine's horizontal frame is x=North, y=West, z=Zenith, while
    # the runtime frame is x=East, y=Up, z=South. North is -South and West is
    # -East, so the permutation is a fixed signed axis swap.
    eus_to_horizontal = np.array(
        [
            [0.0, 0.0, -1.0],  # North  = -South
            [-1.0, 0.0, 0.0],  # West   = -East
            [0.0, 1.0, 0.0],  # Zenith =  Up
        ],
        dtype=np.float64,
    )
    return horizontal_to_equatorial @ eus_to_horizontal


@dataclass(frozen=True, slots=True)
class StarCatalogue:
    """ICRS positions, proper motions, magnitudes, and colours."""

    right_ascension_deg: np.ndarray
    declination_deg: np.ndarray
    proper_motion_ra_cosdec_arcsec_yr: np.ndarray
    proper_motion_dec_arcsec_yr: np.ndarray
    visual_magnitude: np.ndarray
    color_index_bv: np.ndarray
    source_id: str = ""
    source_url: str = ""
    license: str = ""
    retrieved_at: str = ""
    reference_epoch: str = "J2000.0"
    confidence_grade: ConfidenceGrade = ConfidenceGrade.UNVERIFIED
    notes: str = ""

    def __post_init__(self) -> None:
        lengths = {
            len(self.right_ascension_deg),
            len(self.declination_deg),
            len(self.proper_motion_ra_cosdec_arcsec_yr),
            len(self.proper_motion_dec_arcsec_yr),
            len(self.visual_magnitude),
            len(self.color_index_bv),
        }
        if len(lengths) != 1:
            raise ValueError(
                f"catalogue columns have mismatched lengths: {sorted(lengths)}"
            )

    def __len__(self) -> int:
        return len(self.right_ascension_deg)

    @property
    def is_measured(self) -> bool:
        return self.confidence_grade.is_evidence

    # -- astrometry --------------------------------------------------------

    def positions_at(self, moment: datetime) -> tuple[np.ndarray, np.ndarray]:
        """Propagate ICRS positions to ``moment`` by proper motion.

        First order in time, which over the 25 years from J2000 to the event
        and for the largest catalogue proper motions (a few arcseconds per
        year) accumulates well under an arcsecond of error — two orders below
        the 0.05 degree tolerance any position metric applies.
        """

        if moment.tzinfo is None:
            raise ValueError("catalogue epoch must be timezone-aware")
        years = (
            moment.astimezone(timezone.utc) - J2000_EPOCH
        ).total_seconds() / (JULIAN_YEAR_DAYS * 86_400.0)
        declination = self.declination_deg + (
            self.proper_motion_dec_arcsec_yr * years / 3_600.0
        )
        cos_declination = np.maximum(
            np.cos(np.radians(self.declination_deg)), 1e-6
        )
        right_ascension = self.right_ascension_deg + (
            self.proper_motion_ra_cosdec_arcsec_yr
            * years
            / 3_600.0
            / cos_declination
        )
        return right_ascension % 360.0, np.clip(declination, -90.0, 90.0)

    def unit_vectors_at(self, moment: datetime) -> np.ndarray:
        """ICRS unit vectors after proper motion, shaped ``(n, 3)``."""

        right_ascension, declination = self.positions_at(moment)
        ra = np.radians(right_ascension)
        dec = np.radians(declination)
        cos_dec = np.cos(dec)
        return np.stack(
            (cos_dec * np.cos(ra), cos_dec * np.sin(ra), np.sin(dec)), axis=-1
        )

    def apparent_horizontal(
        self,
        moment: datetime,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float = 0.0,
        refraction: astronomy.Refraction = astronomy.Refraction.Normal,
        aberration: bool = True,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Apparent azimuth and altitude in degrees for the whole catalogue.

        One 3x3 multiply for the entire set. Aberration is a single shared
        velocity offset, and refraction depends only on the resulting altitude,
        so neither costs a per-star transform.
        """

        time = astronomy.Time(
            moment.astimezone(timezone.utc)
            .isoformat()
            .replace("+00:00", "Z")
        )
        observer = astronomy.Observer(latitude_deg, longitude_deg, altitude_m)
        directions = self.unit_vectors_at(moment)
        if aberration:
            # First-order annual aberration: the apparent direction tilts
            # toward the observer's velocity by v/c, up to 20.5 arcseconds.
            directions = directions + annual_aberration_velocity(time)[None, :]
            directions /= np.maximum(
                np.linalg.norm(directions, axis=1, keepdims=True), 1e-12
            )
        equatorial_to_horizontal = _rotation_matrix(
            astronomy.Rotation_EQJ_HOR(time, observer)
        )
        horizontal = directions @ equatorial_to_horizontal.T
        altitude = np.degrees(
            np.arcsin(np.clip(horizontal[:, 2], -1.0, 1.0))
        )
        # x is North and y is West, so east is -y and azimuth runs north
        # clockwise through east.
        azimuth = np.degrees(
            np.arctan2(-horizontal[:, 1], horizontal[:, 0])
        ) % 360.0
        if refraction is not astronomy.Refraction.Airless:
            altitude = altitude + np.array(
                [
                    astronomy.RefractionAngle(refraction, float(value))
                    for value in altitude
                ]
            )
        return azimuth, altitude

    # -- appearance --------------------------------------------------------

    def relative_flux(self) -> np.ndarray:
        """Linear flux relative to a zero-magnitude star."""

        return 10.0 ** (-0.4 * np.asarray(self.visual_magnitude, dtype=np.float64))

    def linear_colors(self) -> np.ndarray:
        """Per-star linear RGB from the catalogue's B-V colour index."""

        temperatures = color_temperature_from_bv(self.color_index_bv)
        return np.stack(
            [blackbody_rgb(float(value)) for value in temperatures], axis=0
        )

    def equatorial_flux_map(
        self,
        width: int = 2_048,
        height: int = 1_024,
    ) -> np.ndarray:
        """Rasterise the catalogue into an equirectangular J2000 flux map.

        The map is in the celestial frame, not the observer's, so the sky
        rotates by transforming the view ray rather than by rebuilding this
        texture. Each star is splatted over a small cross so a subpixel source
        survives bilinear reconstruction.
        """

        catalogue = np.zeros((height, width, 3), dtype=np.float32)
        if len(self) == 0:
            return catalogue
        flux = self.relative_flux()
        colors = self.linear_colors()
        column = np.clip(
            (self.right_ascension_deg / 360.0 * width).astype(np.int32),
            0,
            width - 1,
        )
        row = np.clip(
            ((self.declination_deg + 90.0) / 180.0 * height).astype(np.int32),
            0,
            height - 1,
        )
        for offset_x, offset_y, weight in (
            (0, 0, 1.0),
            (-1, 0, 0.28),
            (1, 0, 0.28),
            (0, -1, 0.28),
            (0, 1, 0.28),
        ):
            x = (column + offset_x) % width
            y = np.clip(row + offset_y, 0, height - 1)
            np.add.at(
                catalogue, (y, x), colors * flux[:, None] * weight
            )
        return catalogue

    # -- persistence -------------------------------------------------------

    def save(self, path: Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(
            path,
            right_ascension_deg=self.right_ascension_deg,
            declination_deg=self.declination_deg,
            proper_motion_ra_cosdec_arcsec_yr=(
                self.proper_motion_ra_cosdec_arcsec_yr
            ),
            proper_motion_dec_arcsec_yr=self.proper_motion_dec_arcsec_yr,
            visual_magnitude=self.visual_magnitude,
            color_index_bv=self.color_index_bv,
            metadata=np.array(
                [
                    self.source_id,
                    self.source_url,
                    self.license,
                    self.retrieved_at,
                    self.reference_epoch,
                    self.confidence_grade.value,
                    self.notes,
                ]
            ),
        )
        return path

    @classmethod
    def load(cls, path: Path) -> "StarCatalogue":
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"star catalogue not found: {path}")
        with np.load(path, allow_pickle=False) as data:
            metadata = [str(value) for value in data["metadata"]]
            return cls(
                right_ascension_deg=data["right_ascension_deg"],
                declination_deg=data["declination_deg"],
                proper_motion_ra_cosdec_arcsec_yr=data[
                    "proper_motion_ra_cosdec_arcsec_yr"
                ],
                proper_motion_dec_arcsec_yr=data["proper_motion_dec_arcsec_yr"],
                visual_magnitude=data["visual_magnitude"],
                color_index_bv=data["color_index_bv"],
                source_id=metadata[0],
                source_url=metadata[1],
                license=metadata[2],
                retrieved_at=metadata[3],
                reference_epoch=metadata[4],
                confidence_grade=ConfidenceGrade(metadata[5]),
                notes=metadata[6],
            )

    @classmethod
    def load_if_present(
        cls, path: Path = DEFAULT_CATALOGUE_PATH
    ) -> "StarCatalogue | None":
        """Return the catalogue, or ``None`` when no data has been imported."""

        try:
            return cls.load(path)
        except (FileNotFoundError, KeyError, ValueError):
            return None

    def summary(self) -> dict[str, object]:
        return {
            "stars": len(self),
            "source_id": self.source_id,
            "source_url": self.source_url,
            "license": self.license,
            "retrieved_at": self.retrieved_at,
            "reference_epoch": self.reference_epoch,
            "confidence_grade": self.confidence_grade.value,
            "magnitude_range": [
                float(np.min(self.visual_magnitude)),
                float(np.max(self.visual_magnitude)),
            ]
            if len(self)
            else [],
            "notes": self.notes,
        }
